FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app

COPY requirements.lock /tmp/requirements.lock
RUN pip install --no-cache-dir -r /tmp/requirements.lock

COPY src/ocean_pipeline /app/ocean_pipeline
WORKDIR /app

EXPOSE 8000
CMD ["uvicorn","ocean_pipeline.api:app","--host","0.0.0.0","--port","8000"]
