FROM docker.io/library/eclipse-temurin:17-jre-jammy

RUN apt-get update \
    && apt-get install -y --no-install-recommends bash python3 python3-pip procps \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd --gid 1001 bigred \
    && useradd --uid 1000 --gid 1001 --create-home bigred

ENV PYTHONUNBUFFERED=1
WORKDIR /opt/zfs/project
USER 1000:1001
